//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report_Pro.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langres() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Report_Pro.Lang.Langres", typeof(Langres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure both sides are balanced.
        /// </summary>
        internal static string msgBlanced {
            get {
                return ResourceManager.GetString("msgBlanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        internal static string msgBlanced_H {
            get {
                return ResourceManager.GetString("msgBlanced_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        internal static string msgConfirmDelete {
            get {
                return ResourceManager.GetString("msgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string msgConfirmDelete_H {
            get {
                return ResourceManager.GetString("msgConfirmDelete_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was Deleted Successfully.
        /// </summary>
        internal static string msgDelete {
            get {
                return ResourceManager.GetString("msgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string msgDelete_H {
            get {
                return ResourceManager.GetString("msgDelete_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number Is Duplicate.
        /// </summary>
        internal static string msgDuplicate {
            get {
                return ResourceManager.GetString("msgDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was Updated Successfully.
        /// </summary>
        internal static string msgEdit {
            get {
                return ResourceManager.GetString("msgEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string msgEdit_H {
            get {
                return ResourceManager.GetString("msgEdit_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the data entered .
        /// </summary>
        internal static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string msgError_H {
            get {
                return ResourceManager.GetString("msgError_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The balance is not enough.
        /// </summary>
        internal static string msgNoBalance {
            get {
                return ResourceManager.GetString("msgNoBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string msgNoBalance_H {
            get {
                return ResourceManager.GetString("msgNoBalance_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data update is not allowed.
        /// </summary>
        internal static string msgNoEdit {
            get {
                return ResourceManager.GetString("msgNoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string msgNoEdit_H {
            get {
                return ResourceManager.GetString("msgNoEdit_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Items there are no Items.
        /// </summary>
        internal static string msgNoItems {
            get {
                return ResourceManager.GetString("msgNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string msgNoItems_H {
            get {
                return ResourceManager.GetString("msgNoItems_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was saved Successfully.
        /// </summary>
        internal static string msgSave {
            get {
                return ResourceManager.GetString("msgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string msgSave_H {
            get {
                return ResourceManager.GetString("msgSave_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to save the data first.
        /// </summary>
        internal static string msgSureSave {
            get {
                return ResourceManager.GetString("msgSureSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string msgSureSave_H {
            get {
                return ResourceManager.GetString("msgSureSave_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Old password does not match.
        /// </summary>
        internal static string oldpassConfirm {
            get {
                return ResourceManager.GetString("oldpassConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password does not match.
        /// </summary>
        internal static string passConfirm {
            get {
                return ResourceManager.GetString("passConfirm", resourceCulture);
            }
        }
    }
}
